### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by pregnantboy** [pregnantboy/lololofi#4]
- [ ] 1. Todo list by the side
- [ ] 2. Focus item auto complets from todo list
- [ ] 3. Tagging with `#` to add to list
- [ ] 4. Untagged items goes to unclassified list
